const productCategories = [
  { value: "smartphones", text: "Smartphones" },
  { value: "laptops", text: "Laptops" },
  { value: "fragrances", text: "Fragrances" },
  { value: "skincare", text: "Skincare" },
  { value: "groceries", text: "Groceries" },
  { value: "home-decoration", text: "Home Decoration" },
  { value: "furniture", text: "Furniture" },
  { value: "tops", text: "Tops" },
  { value: "womens-dresses", text: "Womens Dresses" },
  { value: "womens-shoes", text: "Womens Shoes" },
  { value: "mens-shirts", text: "Mens Shirts" },
  { value: "mens-shoes", text: "Mens Shoes" },
  { value: "mens-watches", text: "Mens Watches" },
  { value: "womens-watches", text: "Womens Watches" },
  { value: "womens-bags", text: "Womens Bags" },
  { value: "womens-jewellery", text: "Womens Jewellery" },
  { value: "sunglasses", text: "Sunglasses" },
  { value: "automotive", text: "Automotive" },
  { value: "motorcycle", text: "Motorcycle" },
  { value: "lighting", text: "Lighting" },
];

const productBrands = [
  { value: "Apple", text: "Apple" },
  { value: "Samsung", text: "Samsung" },
  { value: "OPPO", text: "OPPO" },
  { value: "Huawei", text: "Huawei" },
  { value: "Microsoft Surface", text: "Microsoft Surface" },
  { value: "Infinix", text: "Infinix" },
  { value: "HP Pavilion", text: "HP Pavilion" },
  { value: "Impression of Acqua Di Gio", text: "Impression of Acqua Di Gio" },
  { value: "Royal_Mirage", text: "Royal Mirage" },
  { value: "Fog Scent Xpressio", text: "Fog Scent Xpressio" },
  { value: "Al Munakh", text: "Al Munakh" },
  { value: "Lord - Al-Rehab", text: "Lord - Al-Rehab" },
  { value: "L'Oreal Paris", text: "L'Oreal Paris" },
  { value: "Hemani Tea", text: "Hemani Tea" },
  { value: "Dermive", text: "Dermive" },
  { value: "ROREC White Rice", text: "ROREC White Rice" },
  { value: "Fair & Clear", text: "Fair & Clear" },
];

export { productCategories, productBrands };
