import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { store } from "./redux/store";
import HeaderComponent from "./components/HeaderComponent";
import SidebarComponent from "./components/SidebarComponent";
import { ReduxProvider } from "./redux/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tiga Sepuluh - Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <div className="flex">
            <SidebarComponent />
            <div className="w-full">
              <HeaderComponent />
              <div className="content">{children}</div>
            </div>
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
